export type Challenge = {
    id: number 
    word: string
    tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca interfaces web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  { id: 4, word: "JavaScript", tip: "Linguagem de programação" },
  { id: 5, word: "TypeScript", tip: "Adicionar tipagem ao JS" },
  { id: 6, word: "Node", tip: "Ambiente de execução JS no backend" },
  { id: 7, word: "Python", tip: "Linguagem conhecida por dados e IA" },
  { id: 8, word: "Git", tip: "Sistema de controle de versão" },
  { id: 9, word: "GitHub", tip: "Plataforma de hospedagem de código" },
  { id: 10, word: "Docker", tip: "Plataforma de conteinerização" },
  { id: 11, word: "Database", tip: "Local de armazenamento de dados" },
  { id: 12, word: "SQL", tip: "Linguagem de consulta em banco relacional" },
  { id: 13, word: "MongoDB", tip: "Banco de dados NoSQL orientado a documentos" },
  { id: 14, word: "PostgreSQL", tip: "Banco de dados relacional open-source" },
  { id: 15, word: "Nextjs", tip: "Framework React para renderização web" },
  { id: 16, word: "Vue", tip: "Framework JS progressivo para interfaces" },
  { id: 17, word: "Angular", tip: "Framework mantido pelo Google para SPA" },
  { id: 18, word: "API", tip: "Interface de programação de aplicações" },
  { id: 19, word: "REST", tip: "Estilo arquitetural para serviços web" },
  { id: 20, word: "GraphQL", tip: "Linguagem de consulta e runtime para APIs" },
  { id: 21, word: "JSON", tip: "Formato leve de troca de dados" },
  { id: 22, word: "Tailwind", tip: "Framework CSS utilitário" },
  { id: 23, word: "Sass", tip: "Pré-processador CSS com superpoderes" },
  { id: 24, word: "Bootstrap", tip: "Framework CSS com componentes prontos" },
  { id: 25, word: "Vite", tip: "Ferramenta de build rápida para o frontend" },
  { id: 26, word: "Webpack", tip: "Empacotador de módulos para aplicações web" },
  { id: 27, word: "NPM", tip: "Gerenciador de pacotes do Node.js" },
  { id: 28, word: "Yarn", tip: "Gerenciador de pacotes alternativo ao NPM" },
  { id: 29, word: "Vercel", tip: "Plataforma de hospedagem para frontend" },
  { id: 30, word: "Firebase", tip: "Plataforma do Google para backend como serviço" },
  { id: 31, word: "Supabase", tip: "Alternativa open-source ao Firebase" },
  { id: 32, word: "Prisma", tip: "ORM moderno para Node.js e TypeScript" },
  { id: 33, word: "Redis", tip: "Banco de dados em memória para cache" },
  { id: 34, word: "Kubernetes", tip: "Orquestrador de contêineres em escala" },
  { id: 35, word: "Linux", tip: "Sistema operacional open-source muito usado em servidores" },
  { id: 36, word: "Terminal", tip: "Interface de linha de comando" },
  { id: 37, word: "VSCode", tip: "Editor de código muito popular criado pela Microsoft" },
  { id: 38, word: "Figma", tip: "Ferramenta de design e prototipagem de telas" },
  { id: 39, word: "Jest", tip: "Framework de testes em JavaScript" },
  { id: 40, word: "Cypress", tip: "Ferramenta de testes end-to-end para web" },
  { id: 41, word: "OAuth", tip: "Padrão aberto para autorização de acesso" },
  { id: 42, word: "JWT", tip: "Padrão de token compacto e seguro para autenticação" },
  { id: 43, word: "HTTPS", tip: "Protocolo de comunicação segura na web" },
  { id: 44, word: "DNS", tip: "Sistema que traduz nomes de domínio para IP" },
  { id: 45, word: "Redux", tip: "Biblioteca para gerenciamento de estado global" },
  { id: 46, word: "Zustand", tip: "Gerenciador de estado leve para React" },
  { id: 47, word: "Svelte", tip: "Framework que compila código em tempo de build" },
  { id: 48, word: "Flutter", tip: "Framework do Google para apps multiplataforma" },
  { id: 49, word: "ReactNative", tip: "Framework para criar apps nativos usando React" },
  { id: 50, word: "DevOps", tip: "Cultura que unifica desenvolvimento e operações" },
];